db:
  image: mysql:latest
  environment:
    - MYSQL_DATABASE=koel
    - MYSQL_ROOT_PASSWORD=secret
  env_file: .env

web:
  build: .
  links:
    - db:db
  ports:
    - 5000:80
  volumes:
    - ~/Music:/music
  env_file: .env
  command: apache2-foreground