db:
  image: mysql:latest
  environment:
    - MYSQL_DATABASE=koel
    - MYSQL_ROOT_PASSWORD=secret

web:
  build: .
  links:
    - db:db
  ports:
    - 8000:80
  volumes:
    - ~/Music:/home/koel/media
  command: apache2-foreground